### ISSUE TITLE
ERD 설계

### ISSUE THREAD

**Issue by 40LF0** [40LF0/couple_project_backend#1]

**Comment by 40LF0** [comment]
![image](https://github.com/40LF0/couple_project_backend/assets/96645965/6db41ff0-dccd-4eea-9907-375338136ea8)
위의 그림은 ERD 초안입니다.

아래 내용은 ERD 수정 예정 내용입니다.
1. point history table 추가
2. 문의 사항 table 추가
3. member table에 profile Url 추가
4. 추천 장소 table 추가
  - 추후에 review 장소 후보에 쓰임
  - 어떤 유저가 어떤 장소를 추천 받았는지 저장
5.  review가 data_spot을 바라보지 않는다.
  - 대신, spot1,spot2,spot3에 가게 이름을 기입한다

**Comment by sunnism03** [comment]
![06700970-3832-467F-BF0F-E276BB027774](https://github.com/40LF0/couple_project_backend/assets/112189780/b53fb4cd-948c-4ebe-839e-718c1118cda6)
위 그림은 완성된 ERD입니다.

앞선 회의에서 수정 예정이었던 부분 적용 완료했습니다.

아래 내용은 추가적으로 수정한 부분입니다.

1. date_spot_image, review_image table 추가
2. date_spot table에 mapUrl 추가
3. date_spot_category, date_spot_costBand, date_spot_region table 추가
'가까운 장소 추천' 기능 구현을 위해 옵션 설정 정보를 따로 저장할 table을 생성했습니다
다만 table 수가 너무 늘어나는 것을 방지하기 위해 category, costBand, region table을 분리해서 생성했고 ageBand(나이대)와 in_out(실내/외)은 date_spot에 통합했습니다.
